"""add receipt path to expenses

Revision ID: 267cb97bf663
Revises: 72df422be605
Create Date: 2026-10-05 13:26:37.910052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267cb97bf663'
down_revision: Union[str, Sequence[str], None] = '72df422be605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'receipt_path')
    # ### end Alembic commands ###
